### ISSUE TITLE
Create the sql from a template

### ISSUE THREAD

**Issue by brucellino** [brucellino/fgapi-db#1]
In the task which creates the db , we use a static sql file : 

``` yaml
- name: Ensure  that the db is present
  mysql_db:
    name: all
    login_host: "{{ db_config.ansible_facts.ansible_docker_container.NetworkSettings.IPAddress }}"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: import
    target: "{{ lookup('env','PWD')}}/roles/fgapi-db/files/fgapiserver_db.sql"
```

this has many optional things in it, and is mostly a loop on creating tables with similar info in it. Variables should be specified at the level of a site, especially when it comes to passwords and other sensitive info. 

This static file should be templated out too use some role and group variables.
